Scripts/LyumaAv3Runtime.cs

Context:
VRChat introduces new Animator Parameters:
- TrackingType, Int, Playable, which has 6 legal, non-continuous values: 0, 1, 2, 3, 4, 6. Notice that 5 is not an option.
- VRMode, Int, IK, which is either 1 or 0. This is not a boolean.
- MuteSelf, Bool, Playable.
- InStation, Bool, Playable.
In the main branch:
These Animator Parameters are not available in the "Built-in locomotion inputs" part of the "Lyuma AV3 Runtime" component.
Proposal:
- Rename "Built-in locomotion inputs" section of the "Lyuma AV3 Runtime" component to "Built-in inputs"
- Allow control of TrackingType as an Enumeration dropdown in the "Built-in inputs".
- The enumeration values will be:
- 0: Uninitialized
- 1: GenericRig
- 2: NoFingers
- 3: HeadHands
- 4: HeadHandsHip
- 6: HeadHandsHipFeet
- Allow control of …

Add Animator Parameters introduced in 2020.4.1

---

Editor/LyumaAv3EditorSupport.cs
Editor/LyumaAv3MenuEditor.cs
Editor/LyumaAv3MenuEditor.cs.meta
Scripts/LyumaAv3Emulator.cs
Scripts/LyumaAv3Menu.cs
Scripts/LyumaAv3Menu.cs.meta

Context:
AV3 Emulator allows editing stage values manually for testing purposes.
In a game setting, user inputs are driven by their use of the Expressions menu.
In the main branch:
There is no Expression menu integration in the emulator. The user interaction with the menu cannot be tested.
Proposal:
Add an emulation capable of supporting up to two open Expression menus.
The Expression menus will need to emulate the internal state of the menu.
The user should be able to navigate the menu and their interactions should affect the parameters.
---
The menu will require further development to support "quirks" - behaviors that are not immediately obvious -, which is not part of this proposal. These quirks may include:
- A parameter is changed externally while inside a control or when inside a …

Add Expressions Menu emulator (without quirks emulation)

---

Scripts/LyumaAv3Emulator.cs
Scripts/LyumaAv3Runtime.cs

I would like to merge one small bug fix and a tweak to the Avatars 3.0 Emulator.
- The Random mode on the VRC Parameter Driver for integers was excluding the max value (the int version of Unity.Random.Range is being called for some reason, where max is exclusive).
- Prevent the MissingReferenceException every time Playmode is exited while the Emulator Control is enabled.

Fix Random on VRC Parameter Driver excluding max

---

Scripts/LyumaAv3Runtime.cs

Not sure what the purpose of this line is, but it makes layers with no weight show up when running the simulator, which is inaccurate to how avatars behave in VRChat.

Remove line implicitly setting all layers to active

---

Scripts/LyumaAv3Runtime.cs

The emulator currently locks the AngularY float range from -1 to 1, which is only **0.25%** of the default smooth turning speed in-game. This makes the AngularY float useless to test using this emulator.
This pull request changes the range to be -400 to 400, matching the values seen in game while rotating in VR.
_(you can go even higher with a mouse or spinning irl, but this is a nice reference to develop with)_
This enables me to test Fake Dynamics and other useful things using AngularY outside of the animator window:
https://user-images.githubusercontent.com/37721153/141721427-849eaa09-e8dc-44c2-9ba9-d7bf795ac31f.mp4

AngularY float range to match smooth turn in VR

---

Scripts/LyumaAv3Runtime.cs

This fixes two bugs resulting in contacts and physbone parameters not
working on nonlocal avatars:
1. Because the `emulator` field is null on nonlocal avatars,
`assignPhysBoneParameters()` was not being called.  Here, we update
the condition to consult the parent avatar for nonlocal clones.
2. The parameter assignment seems to happen after the initial value of
the contact is set by the VRCSDK, so the accessor was not being
consulted until the value of the contact changed at least once. Here,
we assign the parameter value explicitly when we change out the
accessor to patch over this race condition. There's probably a
cleaner solution, but I don't understand the order of events well
enough to propose it.
Note: I've not fully tested the PhysBone path here, but it shouldn't
break... I think? …

Fix contact/physbone receivers on nonlocal avatars

---

Scripts/LyumaAv3Runtime.cs

When in play mode without the emulator active (e.g. when uploading),
parameter drivers trigger a lot of error-level logspam. This is a problem,
because it will trigger error pause (and confuse anyone who doesn't know
that error pause is a thing).
This change reduces the loglevel to warning, and avoids issuing the warning
more than once per avatar per play mode transition.

Mitigate logspam from parameter drivers

---

Scripts/LyumaAv3Runtime.cs

As of VRC 2022.2.2p3 (30 August 2022, SDK 2022.08.29.20.48), custom FX Avatar Masks are now uploaded for all layers of the FX controller. The previous behaviour of the top layer's mask being set to a mask that disables all humanoid muscles now only occurs if the mask in the controller is empty.
From the [patch notes](https://docs.vrchat.com/docs/vrchat-202222p3#features-changes-fixes-and-improvements):
> Fixed: user-supplied masks on the FX layer were ignored, and prevented Gesture transform animations from working. Docs updated: https://docs.vrchat.com/docs/playable-layers#fx
And part of the updated documentation:
> The mask in the first FX layer, by default is empty, this will (at avatar init) create a default mask that disables all humanoid muscles, but enables all GameObject …

Update FX Avatar Mask behaviour for VRC 2022.2.2p3

---

Editor/LyumaAv3EditorSupport.cs
Scripts/LyumaAv3Runtime.cs

When writing editor scripts for avatars that run via build hooks, it can be helpful to have them work when the Av3Emulator is running as well. However, currently the Av3Runtime reads a bunch of data from the avatar descriptor in Awake, and there's not a reliable way for external tools to run prior to this point (without modifying the scene permanently).
This change simply invokes the VRCSDK's OnPreProcessAvatar hooks automatically when Av3Runtime initializes to resolve this issue.
This supercedes https://github.com/lyuma/Av3Emulator/pull/59 with a simpler approach.

Invoke avatar preprocessing hooks when initializing the emulator

---

Editor/LyumaAv3EditorSupport.cs

I'm getting this message:
> Failed to resolve animator controller vrc_AvatarV3ActionLayer for Action
Idk where did the `d5aeb52dc5e89244abdb9da8296fad0b` GUID come from, but both Assets- and Packages-based SDKs in the current and a couple of previous versions have this file with `3e479eeb9db24704a828bffb15406520` GUID.
It would probably not give that warning with the Assets-based SDK, if not for the `sSADASASDASD` at the end of the path-based lookup. Alternative fixes for that in #69 and #70.

Fixed Action controller's GUID.

---

Editor/LyumaAv3MenuEditor.cs

87a1d4f adds support for rich text in ParameterizedButton. However previous fix changes style for gui globally (this means buttons on other ui will also have richText support). That is not good so I fixed this problem.
To avoid creating GUIStyle every frame, I'm using Styles inner class which is used generally in UnityCsReference. e.g. [here](https://github.com/Unity-Technologies/UnityCsReference/blob/a6fa5178d090c0c727b4e0b03e324c118318c3cd/Editor/Mono/GUI/Toolbar.cs#L37C2-L45)
Because instantiating GUIStyle is not allowed outside of GUI callbacks we cannot initialize GUIStyle in static initializer of Editor class. (editor class will be initialized outside of GUI callbacks). 
Instead, I can use separated class to initialize a class in the GUI callback if we don't access that class …

fix: av3emu changed gui skin globally

---

Editor/LyumaAv3EditorSupport.cs

The initial path-based lookup doesn't work currently because of the (debug?) `sSADASASDASD` at the end anyway.
If you don't wanna get rid of the path-based lookup, an alternative fix is in #70 .

Cleaned animator lookup to only use the GUIDs.

---

Runtime/Scripts/LyumaAv3Runtime.cs

Because of the way I handled local values, their defaults were not respected. This change should fix that by adding the local parameters to the internal list of parameters (like controller parameters), and checking if they should be synced when we're syncing
Closes #106

Fix nonlocal defaults not being applied

---

Runtime/Scripts/LyumaAv3Runtime.cs

In VRC, when you set the Mouth & Jaw to Animation, it will freeze the viseme value. This PR replicates that behaviour
Fixes #109

Fix viseme tracking behaviour

---

package.json

^3.1.0 means >=3.1.0 < 4.0.0, 
since according to the semantic versioning spec, they shouldn't release any breaking changes in the current major version, so our current version should technically work even with 3.17.56

Change semver dependency version

---

Editor/LyumaAv3EditorSupport.cs
Runtime/Scripts/LyumaAv3Emulator.cs

The proposed workflow now is:
Exit Edit Mode: Disable objects and record list in Av3Emulator
Av3Emulator Start: Loop through objects in list in Av3Emulator, and Run Preprocess Hooks.
WaitForNextFrame: Create mirror clone, AddComponent Av3Runtime, then enable objects (which calls Awake and assigns playable graphs etc?)
Enter Edit Mode: Enable objects in list in Av3Emulator, then clear the list.

Defer initialization until after Start

---

Editor/LyumaAv3MenuEditor.cs

For newly created `VRCExpressionsMenu.Control.Parameter` instances, `parameter.name` will be `null` instead of `""`.
This fixes check for `""` to check for `null` or `""`.
In addition, I extracted the logic to local function and simplified logic

fix: parametersIncorrect not working with null parameter.name

---

Runtime/Scripts/LyumaAv3Runtime.cs

Fixes #137 
Since there is no emulation for friend / non-friend, I make `IsOnFriendsList` always true.
I think it's not good to have some toggle to switch `IsOnFriendsList` because I think camera should be remoed with `IsOnFriendsList` = false avatars.

feat: minimum support for `IsOnFriendsList`

---

Runtime/Scripts/LyumaAv3Runtime.cs

Missed this one when implementing parameter mismatch I guess

Fix bool copy parameter mismatch

---

Runtime/Scripts/LyumaAv3Runtime.cs

We were modifying parent constraints wrong when scale wasn't 1,1,1, since our offsets were in local space but treated as if they were in world space.

Fix scaling offset on parent constraints being wrong with changed scale

---

Runtime/Scripts/LyumaAv3Runtime.cs

if we restart the emulator using the Emulator Control's restart option, it breaks mirror detection (and islocal detection as well)
This fix fixes that by waiting for 1 frame always to make isLocal set on time.
(Note: this always happens when using vrcfury or having preprocessor hooks enabled with it in the project, which is a big portion of all avatars out there)

Fix mirror detection after restart

---

Runtime/Scripts/LyumaAv3Runtime.cs

Since we use a TryGetValue into the float/int/bool array to see if it's the right type, this value shouldnt be set if it isnt a parameter of that type.
In rare cases if you had one parameter with different types across different controllers this could cause errors

Fix types being set wrong

---

Runtime/Scripts/LyumaAv3Runtime.cs

PR #185 caused a regression for non-local clones, causing some of their expression parameters to initialize in animator to 0/false until the first sync, this addresses that by ensuring they initialize to the default value set in expression parameters.
Side note: Clones still initialize with animator default values instead of the expression parameter default, I could not figure out how to address that before the clone appeared, I have tried inserting `SetTypeWithMismatch` calls at https://github.com/DorCoMaNdO/Av3Emulator/blob/b55c5c2ea8554a4ea2772e68b9dad97df4b3be19/Runtime/Scripts/LyumaAv3Runtime.cs#L1950, verified that the values were set, but the avatar still appeared with the animator default values first, the value changes only applied 2 frames after the clone spawned. Changing the …

Fix non-local clone regression caused by #185.
